// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> An object describing the details and current state of an export to file job. </summary>
    public partial class Export
    {
        /// <summary> Initializes a new instance of <see cref="Export"/>. </summary>
        internal Export()
        {
        }

        /// <summary> Initializes a new instance of <see cref="Export"/>. </summary>
        /// <param name="id"> The export to file job ID. </param>
        /// <param name="createdDateTime"> The start date and time of the export to file job. </param>
        /// <param name="lastActionDateTime"> The date and time of the last change to the export to file job. </param>
        /// <param name="reportId"> The ID of the exported report. </param>
        /// <param name="reportName"> The name of the exported report. </param>
        /// <param name="status"> The current state of the export to file job. </param>
        /// <param name="percentComplete"> Percentage completion of the export job. </param>
        /// <param name="resourceLocation"> The location where the exported file can be retrieved. </param>
        /// <param name="resourceFileExtension"> The file extension of the exported file. </param>
        /// <param name="expirationTime"> The time when the exported file will expire. </param>
        internal Export(string id, DateTimeOffset? createdDateTime, DateTimeOffset? lastActionDateTime, Guid? reportId, string reportName, ExportStatus? status, int? percentComplete, string resourceLocation, string resourceFileExtension, DateTimeOffset? expirationTime)
        {
            Id = id;
            CreatedDateTime = createdDateTime;
            LastActionDateTime = lastActionDateTime;
            ReportId = reportId;
            ReportName = reportName;
            Status = status;
            PercentComplete = percentComplete;
            ResourceLocation = resourceLocation;
            ResourceFileExtension = resourceFileExtension;
            ExpirationTime = expirationTime;
        }

        /// <summary> The export to file job ID. </summary>
        public string Id { get; }
        /// <summary> The start date and time of the export to file job. </summary>
        public DateTimeOffset? CreatedDateTime { get; }
        /// <summary> The date and time of the last change to the export to file job. </summary>
        public DateTimeOffset? LastActionDateTime { get; }
        /// <summary> The ID of the exported report. </summary>
        public Guid? ReportId { get; }
        /// <summary> The name of the exported report. </summary>
        public string ReportName { get; }
        /// <summary> The current state of the export to file job. </summary>
        public ExportStatus? Status { get; }
        /// <summary> Percentage completion of the export job. </summary>
        public int? PercentComplete { get; }
        /// <summary> The location where the exported file can be retrieved. </summary>
        public string ResourceLocation { get; }
        /// <summary> The file extension of the exported file. </summary>
        public string ResourceFileExtension { get; }
        /// <summary> The time when the exported file will expire. </summary>
        public DateTimeOffset? ExpirationTime { get; }
    }
}
