// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Microsoft.PowerBI.Api.Models
{
    /// <summary> A Power BI report. The API returns a subset of the following list of report properties. The subset depends on the API called, caller permissions, and the availability of data in the Power BI database. </summary>
    public partial class Report : ReportBaseProperties
    {
        /// <summary> Initializes a new instance of <see cref="Report"/>. </summary>
        /// <param name="id"> The report ID. </param>
        internal Report(Guid id) : base(id)
        {
        }

        /// <summary> Initializes a new instance of <see cref="Report"/>. </summary>
        /// <param name="id"> The report ID. </param>
        /// <param name="name"> The name of the report. </param>
        /// <param name="datasetId"> The dataset ID of the report. </param>
        /// <param name="appId"> The app ID, returned only if the report belongs to an app. </param>
        /// <param name="description"> The report description. </param>
        /// <param name="reportType"> The report type. </param>
        /// <param name="originalReportId"> The actual report ID when the workspace is published as an app. </param>
        /// <param name="isOwnedByMe"> Determine if the report is created by the current user. </param>
        internal Report(Guid id, string name, string datasetId, string appId, string description, ReportBasePropertiesReportType? reportType, Guid? originalReportId, bool? isOwnedByMe) : base(id, name, datasetId, appId, description, reportType, originalReportId, isOwnedByMe)
        {
        }
    }
}
